# CHANGEME: Set these variable to your liking
title: Logi.Casa Input Controller
description: Powered by ESPHome and ESP Web Tools
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
